完成
OoMorizono/meal_app pull request #1
Opened 2021-10-10 09:08 UTC by OoMorizono

2021-10-13 20:31 UTC, kazu-taka requested changes
@OoMorizono 
とても良いコードだと思います！
date_diffの件だけ回答お願いします🙏

2021-10-13 20:31 UTC, kazu-taka commented on app/Http/Controllers/LikeController.php
> +            $request->session()->regenerateToken();
@OoMorizono 
二重送信対応いいですね✨

2021-10-13 20:31 UTC, kazu-taka commented on database/factories/PostFactory.php
> +            'user_id' => Arr::random(Arr::pluck(User::all(), 'id')),
@OoMorizono 
ランダムにしたい場合は、次回以降`inRandomOrder`を使ってみて下さい✨
https://webty.jp/staffblog/production/post-2184/

2021-10-13 20:31 UTC, kazu-taka commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
@OoMorizono 
このdate_diffはどこで定義してるメソッドですかね！？
見つけられませんでした^^;

2021-10-13 23:23 UTC, OoMorizono commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
及川さんのほぼ参考にしたので､どこで定義しているかわからないです｡
只､carbonをダウンロードしたので､そちらで用意されたメソッドなのかなと勝手に解釈していました｡

2021-10-13 23:23 UTC, OoMorizono commented on database/factories/PostFactory.php
> +            'user_id' => Arr::random(Arr::pluck(User::all(), 'id')),
ありがとうございます!

2021-10-13 23:31 UTC, OoMorizono commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
恥ずかしながら､及川さんのほぼ参考にしたので､どこで定義しているかわからないです汗
只､carbonをダウンロードしたので､そちらで用意されたメソッドなのかなと勝手に解釈していました｡

2021-10-13 23:56 UTC, OoMorizono commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
おそらく､post model のこの関数です!

2021-10-13 23:57 UTC, OoMorizono commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
public function GetDateDiffAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans(now());
    }

2021-10-14 00:05 UTC, kazu-taka commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
@OoMorizono 
ありがとうございます！
モデルすっかり見逃してました^^;
確実にこのアクセサです✨

2021-10-14 01:34 UTC, OoMorizono commented on resources/views/posts/index.blade.php
> +                        <span class="text-red-400">{{ $post->date_diff }}</span>
早速のご連絡ありがとうございます!
マージして参ります!

2021-10-14 01:34 UTC, merged